# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Joint Trajectory Controller -------------------------------
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
       - jaco2_joint_1
       - jaco2_joint_2
       - jaco2_joint_3
       - jaco2_joint_4
       - jaco2_joint_5
       - jaco2_joint_6
   constraints:
       goal_time: 5.0  # Unusually high
       #stopped_velocity_tolerance: 0.4 # Defaults to 0.01
       jaco2_joint_1:
           trajectory: 0.60
           goal:       0.15
       jaco2_joint_2:
           trajectory: 0.60
           goal:       0.15
       jaco2_joint_3:
           trajectory: 0.60
           goal:       0.15
       jaco2_joint_4:
           trajectory: 0.60
           goal:       0.15
       jaco2_joint_5:
           trajectory: 0.60
           goal:       0.15
       jaco2_joint_6:
           trajectory: 0.60
           goal:       0.15

    # gains:
    #   left_s0: {p: 3.0,  i: 0.01, d: 0.1, i_clamp: 1}
    #   left_s1: {p: 3.0,  i: 0.01, d: 0.1, i_clamp: 1}
    #   left_e0: {p: 3.0,  i: 0.01, d: 0.1, i_clamp: 1}
    #   left_e1: {p: 3.0,  i: 0.01, d: 0.1, i_clamp: 1}
    #   left_w0: {p: 10.0,  i: 0.01, d: 0.1, i_clamp: 1}
    #   left_w1: {p: 3.0,  i: 0.01, d: 0.1, i_clamp: 1}
    #   left_w2: {p: 3.0,  i: 0.01, d: 0.1, i_clamp: 1}

    # state_publish_rate:  50 # Defaults to 50
    # action_monitor_rate: 20 # Defaults to 20
    #hold_trajectory_duration: 0 # Defaults to 0.5

# TODO: Gripper controller for the fingers 

